
#set-option -g detach-on-destroy off
set -g default-terminal "tmux-256color"
set -as terminal-features ",ghostty:RGB"
set -as terminal-features ",xterm*:RGB"
set -g mouse on
set -g escape-time 0  # disable delays on escape sequences

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
bind-key b set-option status

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'

#set -g status-position top
set -g @minimal-tmux-status "top"

# Inactive windows
set -g window-status-style "fg=#6c7086,bg=default"

# Current window
set -g window-status-current-style "fg=#ffffff,bg=default"

# Optional: make inactive tabs even dimmer
set -g window-status-format "#[fg=#6c7086] #I:#W "

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Aliases for creating new splits

bind "|" split-window -h -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"

bind -n M-l send-keys C-l

set-window-option -g mode-keys vi
setw -g mode-keys vi

# keybindings for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Display popups

bind C-g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-s display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "gurk"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-f display-popup \
  -w 80% \
  -h 80% \
  -E 'rmpc'
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

# bind-key C-k run-shell "sesh connect \"$(
#   sesh list --icons | fzf-tmux -p 80%,70% \
#     --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
#     --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
#     --bind 'tab:down,btab:up' \
#     --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
#     --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
#     --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
#     --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
#     --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
#     --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
#     --preview-window 'right:55%' \
#     --preview 'sesh preview {}'
# )\""

bind-key C-k run-shell "zsh -ic sesh_picker"

##### Display Menu ##### 
# Yo dayze are numbered
bind C-d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  ".zshrc"            z  "display-popup -E 'nvim ~/.zshrc'" \
  "tmux.conf"        t  "display-popup -E 'nvim ~/.config/tmux/tmux.conf'" \
  "Exit"              q  ""

run '~/.tmux/plugins/tmp/tmp'
