set -g default-terminal "tmux-256color"
set -as terminal-features ",ghostty:RGB"
set -as terminal-features ",xterm*:RGB"
set -g mouse on
set -g escape-time 0  # disable delays on escape sequences

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'wfxr/tmux-fzf-url'

set -g status-position top

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Aliases for creating new splits

bind "|" split-window -h -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"

bind -n M-l send-keys C-l

set-window-option -g mode-keys vi
setw -g mode-keys vi

# keybindings for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Display popups

bind C-g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-s display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "gurk"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-f display-popup \
  -w 80% \
  -h 80% \
  -E 'rmpc'
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

##### Display Menu ##### 

bind C-d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  ".zshrc"            z  "display-popup -E 'nvim ~/.zshrc'" \
  "tmux.conf"        t  "display-popup -E 'nvim ~/.config/tmux/tmux.conf'" \
  "Exit"              q  ""

run '~/.tmux/plugins/tmp/tmp'
