#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

# open the file manager
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

# Configs
[[session]]
name = "tmuxconfig"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "zshconfig"
path = "~/dotfiles"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "seshconfig"
path = "~/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "nvimconfig"
path = "~/dotfiles/.config/nvim/lua"
startup_command = "nvim ."

[[session]]
name = "homebrowse"
path = "~/"
startup_command = "yazi"

# run a script to startup a node project
[[session]]
path = "~/Documents/git/lab/naturalis/bii/tol/docker-compose-tol"
startup_command = "~/.config/sesh/scripts/make_dev"

[[session]]
name = "gurk"
startup_command = "gurk"

[[session]]
name = "update brew"
startup_command = "brew update && brew upgrade -y && exit 0"

[default_session]
startup_command = "nvim -c ':Telescope find_files'"
