#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[window]]
name = "tuxedo"
startup_script = "tuxedo todo.txt"

# Configs
[[session]]
name = "tmuxconfig"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "zshconfig"
path = "~/dotfiles"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "seshconfig"
path = "~/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/dotfiles/.config/sesh/sesh.toml"

[[session]]
name = "neovim config"
path = "~/dotfiles/.config/nvim"
startup_command = "nvim ."
windows = ["tuxedo"]

# TODO: Fix
# run a script to startup a node project
[[session]]
path = "~/Documents/git/lab/naturalis/bii/tol/docker-compose-tol"
startup_command = "~/.config/sesh/scripts/make_dev"

[[session]]
name = "s3-devkit"
path = "~/Documents/git/lab/naturalis/s3-devkit/"
startup_command = "source ~/.config/sesh/scripts/activate_venv && nvim -c ':Telescope find_files'"

[[session]]
name = "update brew"
preview_command = ""
startup_command = "brew update && brew upgrade -y && exit 0"

[default_session]
startup_command = "nvim -c ':Telescope find_files'"
