return {}
-- return {
--   -- Mason install
--   {
--     "williamboman/mason.nvim",
--     opts = {
--       ensure_installed = {
--         "ltex-ls-plus",
--       },
--     },
--   },
--
--   -- Vim spell checking
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       spell = {
--         enabled = true,
--         lang = { "en", "nl" },
--       },
--     },
--   },
--
--   -- LTeX
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         ltex_plus = {
--           filetypes = {
--             "markdown",
--             "text",
--             "gitcommit",
--           },
--
--           settings = {
--             ltex = {
--               -- LTeX's `auto` detection is coarse and often falls back to English.
--               -- Keep grammar checking in Dutch by default and use Vim spell for bilingual spelling.
--               language = "nl-NL",
--               motherTongue = "en-US",
--               checkFrequency = "save",
--
--               additionalRules = {
--                 enablePickyRules = true,
--               },
--
--               -- Disable LTeX's own spelling rules so Dutch/English mixed text is handled by Vim spell instead.
--               -- Vim spell supports multiple spell languages at once: spelllang=en,nl.
--               disabledRules = {
--                 ["en-US"] = { "MORFOLOGIK_RULE_EN_US" },
--                 ["en-GB"] = { "MORFOLOGIK_RULE_EN_GB" },
--                 ["nl-NL"] = { "MORFOLOGIK_RULE_NL_NL" },
--               },
--             },
--           },
--
--           keys = {
--             {
--               "<leader>uln",
--               function()
--                 vim.lsp.buf_notify(0, "workspace/didChangeConfiguration", {
--                   settings = {
--                     ltex = {
--                       language = "nl-NL",
--                     },
--                   },
--                 })
--                 vim.notify("LTeX language set to Dutch")
--               end,
--               desc = "LTeX: Dutch",
--             },
--             {
--               "<leader>ule",
--               function()
--                 vim.lsp.buf_notify(0, "workspace/didChangeConfiguration", {
--                   settings = {
--                     ltex = {
--                       language = "en-US",
--                     },
--                   },
--                 })
--                 vim.notify("LTeX language set to English")
--               end,
--               desc = "LTeX: English",
--             },
--           },
--         },
--       },
--     },
--   },
-- }
